apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler 
metadata:
  name: users-blog-hpa 
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: users-blog
minReplicas: 1 # Minimum number of replicas 
maxReplicas: 10 # Maximum number of replicas 
metrics:
- type: Resource 
  resource: 
    name: cpu 
    target:
    type: Utilization 
    averageUtilization: 50 # Scale when average CPU usage exceeds 50%